### ISSUE TITLE
Potentially upgrade to latest OpenOakland OpenBudget framework

### ISSUE THREAD

**Issue by feydan** [code4sac/openbudgetsac.org#15]
Open Oakland has updated their Open Budget site with some new technology (Node/React/Jade instead of Ruby/Jekyll/Markdown): https://github.com/openoakland/openbudgetoakland

Explore the work necessary to rebuild OpenBudgetSac with the latest Open Budget framework.  My initial sense is this is a significant amount of work, but the new site does have some interesting new visualizations and tools.

**Comment by gavindeschutter** [comment]
@feydan are you actively working on this? I’m open to 🍐ing on scope.

**Comment by feydan** [comment]
@gavindeschutter that would be great!  Want to come to the next Code For Sac meetup? https://www.meetup.com/Code4Sac/
