### ISSUE TITLE
 [Node/React upgrade] Transform data and treemaps

### ISSUE THREAD

**Issue by feydan** [code4sac/openbudgetsac.org#17]
Transform the current data sets to conform to the formats consumed in https://github.com/openoakland/openbudgetoakland

There seems to be three different types of data sets:
1. compare
2. flow
3. tree

If there's a lot of work here, break it out into separate issues

**Comment by feydan** [comment]
The compare page is significantly more complicated due to its reliance on an external api.  I outlined the work here: https://github.com/code4sac/openbudgetsac.org/issues/21

**Comment by feydan** [comment]
I started on this task by trying to break out one fiscal year's worth of flow data.  It is not as simple as replacing the data files.  There are some assumptions built into the code regarding department names and specific strings that are not in our data files.

**Comment by DonaldBrower** [comment]
[New flow graphs](http://openbudgetsac.org/2015-18-adopted-budget-flow/)

[New treemaps](http://openbudgetsac.org/2013-14-adopted-budget-tree/#fy18.expensel)
