### ISSUE TITLE
 [Node/React upgrade] Make copy changes to openbudgetsac

### ISSUE THREAD

**Issue by feydan** [code4sac/openbudgetsac.org#18]
After we get the new framework on a branch, we need to change all of the copy titles, text, links, and logs from openbudgetoakland to openbudget sac.  https://github.com/openoakland/openbudgetoakland

**Comment by feydan** [comment]
Also make sure to update things like Google Analytics tracking.

**Comment by mayanhavoc** [comment]
Hey everyone, sorry I missed yesterdays meet. I am mostly finished with the changes to openbudgetsac (at least Im pretty sure I am). I will try to push my changes later today.

**Comment by createHernandez** [comment]
Copy still needs to be updated.
