### ISSUE TITLE
 [Node/React upgrade] Publish new site

### ISSUE THREAD

**Issue by feydan** [code4sac/openbudgetsac.org#19]
Once the data and copy changes are in place, we can merge the changes into master and publish the new site.  There are already scripts to publish the site to the gh-pages branch -- ensure it works properly.

**Comment by DonaldBrower** [comment]
The new site is published. The [release-eleventy](https://github.com/code4sac/openbudgetsac.org/tree/release-eleventy) branch has the latest version of the code.  It also has a github action set up so whenever code is pushed to it, a github action will kick in and deploy the site to the gh-pages branch.  it wipes that branch clean everytime.  [gh-pages@dd49b17](https://github.com/code4sac/openbudgetsac.org/commit/dd49b17b6bdc7edb6180a6d8836d430d37499997) is the final version of the original codebase.
