### ISSUE TITLE
Update with new data for 2016-2017

### ISSUE THREAD

**Issue by mcnnowak** [code4sac/openbudgetsac.org#2]
Looks like this data is old. Is there a new budget available? Does the city make this information available publicly in some easily readable format?

**Comment by joelrip** [comment]
The data comes from the city's open data portal, and unfortunately, they haven't published any new budget information since the data set we used for this. http://data.cityofsacramento.org/datasets/city-of-sacramento-budget

**Comment by joelrip** [comment]
Just an update: have exchanged emails with City staff, and they have settled on a schema to use for future budget data exports that should facilitate more frequent updating. Still don't know when that's going to happen, but they're working on it.

**Comment by joelrip** [comment]
The city has finally put new data on their open data portal! Anyone who wants to contribute to updating the site, here's the data to work from: http://data.cityofsacramento.org/datasets/approved-budget-fy-2015-fy-2018

**Comment by jeffgreenca** [comment]
Hello.  Are you looking for someone to parse the CSV from the city into the format the app can handle, or directly integrate with the city's new-looking API?

**Comment by joelrip** [comment]
@jeffgreenca We're looking for people to create new visualizations with the new data, and to update the existing visualizations. Of the three that already exist on the page, I think only the treemap doesn't have a current owner. So getting new data into that would be valuable. Looks like he pulled that in in json format. https://github.com/code4sac/sac-city-budget-treemap

**Comment by mcnnowak** [comment]
I've got some experience with D3 and graphing and things like that. What sort of visualizations are you looking for besides the tree graph?

**Comment by joelrip** [comment]
@mcnnowak We're looking for people to bring their creative ideas! Some examples:

http://openbudgetoakland.org/
http://prototype.budgetpedia.ca/datastory-surpluses-deficits.php
http://www.phila.gov/openbudget/

Feel free to try out whatever strikes you as valuable.

**Comment by joelrip** [comment]
Oh, and if anyone can make this happen, you're my best friend.

http://www.nytimes.com/interactive/2012/02/13/us/politics/2013-budget-proposal-graphic.html

**Comment by nharrisanalyst** [comment]
ok I am going to devote some time to this this weekend

**Comment by BrianHenryIE** [comment]
The beginning of some Python, intended to be added as a [Git hook](https://githooks.com/), i.e. regenerate the JSON from the newest csv file each time master is updated.

```
import os
import csv

cwd = '/Users/BrianHenryIE/Sites/openbudgetsac-csv-to-json/data'

for filename in os.listdir(cwd):

    print(filename)

    if filename.endswith('.csv'):

        with open('filename', newline='') as csvfile:
            csvreader = csv.reader(csvfile, delimiter=',', quotechar='"')
            headers = csvreader[0]
            data_lines = []
            for row in csvreader:
                # Each row read from the csv file is returned as a list of strings.
                data_line = {}
                for index, value in enumerate(row):
                    data_line[headers[index]] = value

                data_lines.append(data_line)

            # drop the first item in data_lines since it's just the headers with the headers
```

**Comment by jeffgreenca** [comment]
If you can use the `pandas` library you might just:
```
import pandas
import glob

for fname in glob.glob("/path/to/*.csv"):
    with open(fname, 'r') as f:
        df = pandas.read_csv(fname, <some options>)
        data = df.json(<possibly some options>)
```

(as a starting point, hope this helps)

**Comment by feydan** [comment]
This project (cleaning folder) has some scripts that may have generated the original json tree structure in this project's data folder.  Perhaps we can use/adapt it for the new csv data: https://github.com/ak2040/Sac-Budget-Treemap

**Comment by L0per** [comment]
The treemap has been updated with the 2017/2018 budget and it looks like the only other one that needs to be updated is the "Build your own Custom Queries" page. Perhaps we can close this issue and create a new issue specific to the "Build your own Custom Queries" page?

**Comment by feydan** [comment]
Thanks for getting this updated!  
I created a new issue here: https://github.com/code4sac/openbudgetsac.org/issues/13
