### ISSUE TITLE
use same treemap implementation as Philadelphia open budget viz

### ISSUE THREAD

**Issue by markmatney** [code4sac/openbudgetsac.org#3]
City of Philadelphia has an [open budget visualization](http://www.phila.gov/openbudget/) based on [this](https://github.com/tpreusse/open-budget). I think the current rectangular visualization is confusing when there is a quantity represented by a rectangle whose height is less than another rectangle representing a smaller quantity (e.g., for 2015-16, more money was allocated to "Fire" than "Debt Service", but the rectangle for "Debt Service" has a larger y dimension).

**Comment by joelrip** [comment]
FYI, the City has finally updated their budget data on the open data portal. If you'd like to take a crack at implementing this with the new data, we'd love to see it. http://data.cityofsacramento.org/datasets/approved-budget-fy-2015-fy-2018
