### ISSUE TITLE
Update data to latest

### ISSUE THREAD

**Issue by feydan** [code4sac/openbudgetsac.org#30]
Since we closed out https://github.com/code4sac/openbudgetsac.org/issues/29, we now have access data that we didn't have access to before (years 2018-2022).  We should update the application to use this data.

**Comment by feydan** [comment]
Updated data is here: https://data.cityofsacramento.org/datasets/7b8b3680603c4894bd3faaa41c986c7c_0/explore

**Comment by sebroad** [comment]
I've added the relevant datafile in a recent PR #53 . This data still needs to be transformed into formats required by each of the visualizations.
